variable TEMP           equal   310.0
variable PRESS 		equal   0.0

variable SEED2   	equal   $( v_SEED + 1099 )
variable SEED3  	equal   $( v_SEED + 80192 ) 
variable SEED4  	equal   $( v_SEED + 7102 )
variable SEED5 		equal   $( v_SEED + 30192 )

variable PID   		equal   0
variable CID   		equal 	1

include "lipid.ff"
include "system.init"

read_data eq${PID}.data

include "system.settings"

group GAG type <= 70
group RNA type 71
group MEM type <> 72 77
group SUB type 26 31 61 66 
group IP6 type 78

neigh_modify exclude molecule/intra GAG

timestep  50.0 

fix b1 all balance 5000 0.95 shift xy 15 1.03 #weight time 0.8

dump 1 GAG atom 5000000 dump${CID}.lammpstrj
dump_modify 1 sort id

dump 2 SUB atom 1000000 sub${CID}.lammpstrj
dump_modify 2 sort id

compute 1 all pair gauss/wall

fix 1  all    nve
fix 2  GAG    langevin ${TEMP} ${TEMP} 50000.0 ${SEED2} zero yes
fix 3  RNA    langevin ${TEMP} ${TEMP} 50000.0 ${SEED3} zero yes
fix 4  MEM    langevin ${TEMP} ${TEMP} 50000.0 ${SEED4} zero yes

fix 5  GAG    cluster_switch ${MID} 0 17.5 ${SEED4} rateFreq 500000 rateFile rates.txt contactFile contacts.txt 

thermo 50000
thermo_style  custom  step spcpu  temp  ke pe etotal  epair c_1 lx ly lz  pxx pyy pzz f_5[1] f_5[2] f_5[3] f_5[4] f_5[5] f_5[6] f_5[7] 

restart 1000000 restart.1 restart.2

run 25000000

write_dump all atom eq${CID}.lammpstrj
write_restart eq${CID}.restart
write_data eq${CID}.data nocoeff
