    units      	   real      
    atom_style     full      
    pair_style     hybrid/overlay soft 50.0 gauss/wall 30.0 gauss/cut 25.0 coul/debye 0.1274 40.0 lj/cut/soft 2 0.5 40.0 john4
    bond_style     harmonic
    angle_style    harmonic
    neighbor  	   10.0 bin
    neigh_modify   every 1 delay 0 check yes
    boundary 	   p p p
    processors 	   * * 2
    special_bonds  lj 0.0 1.0 1.0
    dielectric 	   17.5
    
